src/main/java/com/itdaima/modules/front/entity/Say.java
package com.itdaima.modules.front.entity;

import com.itdaima.common.persistence.DataEntity;
import com.itdaima.modules.sys.entity.User;

/**
 * Created by Administrator on 2017/7/27.
 * 说说
 */
public class Say extends DataEntity<Say> {
    private static final long serialVersionUID = 1L;
    private String content; //说说内容
    private User user; //用户
    private String agoDate;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getAgoDate() {
        return agoDate;
    }

    public void setAgoDate(String agoDate) {
        this.agoDate = agoDate;
    }
}

src/main/java/com/itdaima/modules/sys/entity/User.java
/**
 *
 */
package com.itdaima.modules.sys.entity;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;

import com.itdaima.common.config.Global;
import com.itdaima.common.utils.StringUtils;
import com.itdaima.modules.sys.utils.UserUtils;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.common.collect.Lists;
import com.itdaima.common.persistence.DataEntity;
import com.itdaima.common.supcan.annotation.treelist.cols.SupCol;
import com.itdaima.common.utils.Collections3;
import com.itdaima.common.utils.excel.annotation.ExcelField;
import com.itdaima.common.utils.excel.fieldtype.RoleListType;

/**
 * 用户Entity
 * @author ThinkGem
 * @version 2013-12-05
 */
public class User extends DataEntity<User> {

	private static final long serialVersionUID = 1L;
	private String loginName;// 登录名
	private String password;// 密码
	private String name;	// 姓名
	private String email;	// 邮箱
	private String phone;	// 电话
	private String mobile;	// 手机
	private String loginIp;	// 最后登陆IP
	private Date loginDate;	// 最后登陆日期
	private String loginFlag;	// 是否允许登陆
	private String photo;	// 头像

	private String oldLoginName;// 原登录名
	private String newPassword;	// 新密码
	
	private String oldLoginIp;	// 上次登陆IP
	private Date oldLoginDate;	// 上次登陆日期

	private String roleId;	//角色id

	private Role role;

	private Boolean isSlectRole = true;

	public User() {
		super();
		this.loginFlag = Global.YES;
	}
	
	public User(String id){
		super(id);
	}

	public User(String id, String loginName){
		super(id);
		this.loginName = loginName;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getLoginFlag() {
		return loginFlag;
	}

	public void setLoginFlag(String loginFlag) {
		this.loginFlag = loginFlag;
	}

	@SupCol(isUnique="true", isHide="true")
	@ExcelField(title="ID", type=1, align=2, sort=1)
	public String getId() {
		return id;
	}

	@Length(min=1, max=100, message="登录名长度必须介于 1 和 100 之间")
	@ExcelField(title="登录名", align=2, sort=30)
	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@JsonIgnore
	@Length(min=1, max=100, message="密码长度必须介于 1 和 100 之间")
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Length(min=1, max=100, message="姓名长度必须介于 1 和 100 之间")
	@ExcelField(title="姓名", align=2, sort=40)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Email(message="邮箱格式不正确")
	@Length(min=0, max=200, message="邮箱长度必须介于 1 和 200 之间")
	@ExcelField(title="邮箱", align=1, sort=50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Length(min=0, max=200, message="电话长度必须介于 1 和 200 之间")
	@ExcelField(title="电话", align=2, sort=60)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Length(min=0, max=200, message="手机长度必须介于 1 和 200 之间")
	@ExcelField(title="手机", align=2, sort=70)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@ExcelField(title="备注", align=1, sort=900)
	public String getRemarks() {
		return remarks;
	}

	@ExcelField(title="创建时间", type=0, align=1, sort=90)
	public Date getCreateDate() {
		return createDate;
	}

	@ExcelField(title="最后登录IP", type=1, align=1, sort=100)
	public String getLoginIp() {
		return loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@ExcelField(title="最后登录日期", type=1, align=1, sort=110)
	public Date getLoginDate() {
		return loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	public String getOldLoginName() {
		return oldLoginName;
	}

	public void setOldLoginName(String oldLoginName) {
		this.oldLoginName = oldLoginName;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	public String getOldLoginIp() {
		if (oldLoginIp == null){
			return loginIp;
		}
		return oldLoginIp;
	}

	public void setOldLoginIp(String oldLoginIp) {
		this.oldLoginIp = oldLoginIp;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getOldLoginDate() {
		if (oldLoginDate == null){
			return loginDate;
		}
		return oldLoginDate;
	}

	public void setOldLoginDate(Date oldLoginDate) {
		this.oldLoginDate = oldLoginDate;
	}

	public Role getRole() {
		if (this.isSlectRole){
			Role role = UserUtils.getRoleByLoginName(this.loginName);
			if (role != null) {
				return role;
			}
		}
		return null;
	}

	public boolean isAdmin(){
		return isAdmin(this.id);
	}
	
	public static boolean isAdmin(String id){
		return id != null && "1".equals(id);
	}

	public String getRoleId() {
		return roleId;
	}

	/*public String getRoleId() {
            if(this.getRole()!=null){
                String roleId = this.getRole().getId();
                if(StringUtils.isNotBlank(roleId)){
                    return roleId;
                }
            }
            return null;
        }

    */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
	public void setRole(Role role) {
		this.role = role;
	}

	public Boolean getIsSlectRole() {
		return isSlectRole;
	}

	public void setIsSlectRole(Boolean isSlectRole) {
		this.isSlectRole = isSlectRole;
	}

	@Override
	public String toString() {
		return id;
	}
}

src/main/java/com/itdaima/modules/blog/web/BlogController.java
package com.itdaima.modules.blog.web;

import com.itdaima.common.persistence.Page;
import com.itdaima.common.utils.DateUtils;
import com.itdaima.common.utils.Encodes;
import com.itdaima.common.utils.StringUtils;
import com.itdaima.common.web.BaseController;
import com.itdaima.common.web.Servlets;
import com.itdaima.modules.sys.dao.ArticleDao;
import com.itdaima.modules.sys.entity.Article;
import com.itdaima.modules.sys.entity.Dict;
import com.itdaima.modules.sys.security.SystemAuthorizingRealm.Principal;
import com.itdaima.modules.sys.service.ArticleService;
import com.itdaima.modules.sys.service.DictService;
import com.itdaima.modules.sys.utils.LogUtils;
import com.itdaima.modules.sys.utils.UserUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Date;
import java.util.List;

/**
 * Created by Administrator on 2017/7/21.
 */
@Controller
@RequestMapping(value = "${frontPath}")
public class BlogController extends BaseController {

    @Autowired
    private ArticleService articleService;
    @Autowired
    private ArticleDao articleDao;
    @Autowired
    private DictService dictService;


    /**
     * 博客
     */
    @RequestMapping(value={"/blog${urlSuffix}","/blog/p{pageNo}${urlSuffix}"})
    public String blog(Model model,HttpServletRequest request, HttpServletResponse response,
                       @PathVariable @RequestParam(value = "pageNo",defaultValue = "1") Integer pageNo) {
        model.addAttribute("navbarType", "blog");
        Article article = new Article();
        article.setType("blog");
        Page<Article> page = new Page<Article>(request, response);
        String url = request.getRequestURI();
        url = url.substring(url.indexOf("/p") + 2, url.indexOf(urlSuffix));
        if(StringUtils.isNotBlank(url) && !url.equals("t/blog")){
            pageNo = Integer.parseInt(url);
        }
        page.setPageNo(pageNo);
        page = articleService.findPage(page, article);
        List<Article> list = page.getList();
        for(Article a :list){
            String content = a.getContent();
            List<String> img = StringUtils.getImg(content, a.getTitle());
            a.setImg(img);
            content = StringUtils.abbr(content, 250);
            a.setContent(content);
        }
        model.addAttribute("page", page);
        return "modules/blog/blog";
    }

    /**
     * 发表博客
     */
    @RequestMapping(value="/blogFrom${urlSuffix}")
    public String blogFrom(Model model,String title, String articleType,String content, HttpServletRequest request) {
        Principal principal = UserUtils.getPrincipal();
        if(principal==null){
            return "redirect:frontLogin" + urlSuffix;
        }
        if(StringUtils.isNotBlank(content)){
            content = Encodes.unescapeHtml(content);
            Article article = new Article();
            article.setTitle(title);
            article.setType("blog");
            article.setArticleType(articleType);
            article.setContent(content);
            article.setIsAuditing("0"); //代表需要审核
            article.setHits(0);
            article.preInsert();
            articleDao.insert(article);
            LogUtils.saveLog(Servlets.getRequest(), "发表博客");
            model.addAttribute("message", "博客发表成功！已在审核中...");
        }
        Dict dict = new Dict();
        dict.setType("atricle_type");
        List<Dict> dictList = dictService.findList(dict);
        model.addAttribute("dictList", dictList);
        model.addAttribute("content",content);
        return "modules/blog/blogFrom";
    }
    /**
     * 查看博客详情
     */
    @RequestMapping(value="/blogView/{id}${urlSuffix}")
    public String blogView(Model model, @PathVariable String id) {
        articleService.updateHits(id);
        Article article = articleDao.get(id);
        article.setContent(StringUtils.ImageCode(article.getContent(),article.getTitle()));//重写源代码
        article.setCreateTime(DateUtils.formatDate(article.getCreateDate(), "yyyy-MM-dd HH:mm:ss"));
        model.addAttribute("article",article);
        return "modules/blog/blogView";
    }
}

src/main/java/com/itdaima/modules/front/web/CommentController.java
package com.itdaima.modules.front.web;

import com.google.common.collect.Maps;
import com.itdaima.common.persistence.Page;
import com.itdaima.common.utils.Result;
import com.itdaima.common.utils.StringUtils;
import com.itdaima.common.web.BaseController;
import com.itdaima.modules.front.dao.CommentDao;
import com.itdaima.modules.front.entity.Comment;
import com.itdaima.modules.front.service.CommentService;
import com.itdaima.modules.sys.entity.User;
import com.itdaima.modules.sys.security.SystemAuthorizingRealm.Principal;
import com.itdaima.modules.sys.utils.UserUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;

/**
 * Created by Administrator on 2017/8/2.
 */
@Controller
@RequestMapping(value = "${frontPath}/comment")
public class CommentController extends BaseController {

    @Autowired
    private CommentDao commentDao;
    @Autowired
    private CommentService commentService;

    /**
     * 发表评论
     * @param articleId
     * @param commentContent
     * @param replyUserName
     * @param request
     * @param response
     * @return
     */
    @RequestMapping(value="save")
    @ResponseBody
    public Result save(String articleId, String commentContent, String replyUserName, HttpServletRequest request, HttpServletResponse response) {
        //判断是否已经登录用户
        Principal principal = UserUtils.getPrincipal();
        if(principal == null){
            return Result.warnResult().setMsg("请登录后再评论");
        }
        Comment comment = new Comment();
        if (StringUtils.isNotBlank(replyUserName)) {
            comment.setReplyUserName(replyUserName);
        }
        comment.setArticleId(articleId);
        comment.setContent(commentContent);
        comment.preInsert();
        commentDao.insert(comment);
        return Result.successResult();
    }

    /**
     * 评论展示
     * @param articleId
     * @param request
     * @param response
     * @return
     */
    @RequestMapping(value="commentList")
    @ResponseBody
    public Result commentList(String articleId, Integer pageNo, HttpServletRequest request, HttpServletResponse response) {
        Page<Comment> page = new Page<Comment>(request, response);
        page.setPageNo(pageNo);
        page.setPageSize(5);  //每次显示5条记录
        Comment comment = new Comment();
        comment.setArticleId(articleId);
        page = commentService.findPage(page, comment);
        HashMap<Object, Object> hashMap = Maps.newHashMap();
        hashMap.put("page",page);
        hashMap.put("pageLast",page.getLast());
        return Result.successResult().setObj(hashMap);
    }




}

src/main/java/com/itdaima/modules/front/web/SayController.java
package com.itdaima.modules.front.web;

import com.itdaima.common.utils.Encodes;
import com.itdaima.common.utils.Result;
import com.itdaima.common.web.BaseController;
import com.itdaima.modules.front.dao.SayDao;
import com.itdaima.modules.front.entity.Say;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by Administrator on 2017/7/27.
 * 发表说说
 */
@Controller
@RequestMapping(value = "${frontPath}/say")
public class SayController extends BaseController {
    @Autowired
    private SayDao sayDao;

    @RequestMapping(value="")
    @ResponseBody
    public Result shareView(String sayContent) {
        Say say = new Say();
        sayContent = Encodes.unescapeHtml(sayContent);
        say.setContent(sayContent);
        say.preInsert();
        sayDao.insert(say);
        Result result = Result.successResult();
        result.setMsg("说说发表成功");
        return result;
    }

}

src/main/java/com/itdaima/modules/front/web/UploadController.java
package com.itdaima.modules.front.web;

import com.google.gson.JsonNull;
import com.itdaima.common.utils.FileUploadUtil;
import com.itdaima.common.utils.ImageUploadUtil;
import com.itdaima.common.utils.Result;
import com.itdaima.common.web.BaseController;
import org.activiti.engine.impl.util.json.JSONObject;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by Administrator on 2017/7/19.
 */
@Controller
@RequestMapping(value="${frontPath}/upload")
public class UploadController extends BaseController {

    /**
         *图片上传
         * @param request
         * @param response
         * @param model
         * @return
         */
        @RequestMapping(value = {"uploadImage"})
        public String uploadImage(HttpServletRequest request, HttpServletResponse response, Model model) throws Exception {
            String DirectoryName = "userfiles";
            try {
                ImageUploadUtil.ckeditor(request, response, DirectoryName);
            } catch (IllegalStateException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }

        /**
         *文件上传
         * @return
         */
        @RequestMapping(value = {"uploadFile"})
        @ResponseBody
        public Result uploadFile(HttpServletRequest request,HttpServletResponse response) throws Exception {
            String DirectoryName = "files";
            String imageContextPath = null;
            try {
                imageContextPath = FileUploadUtil.ckeditor(request, response, DirectoryName);
            } catch (IllegalStateException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return Result.successResult().setObj(imageContextPath);

    }
}

src/main/webapp/WEB-INF/views/modules/sys/articleList.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/modules/front/include/taglib.jsp" %>
<html>
<head>
  <meta name="decorator" content="admin_boostrap3"/>
  <title>文章管理</title>
  <script src="${ctxStatic}/common/itdaima.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    function page(n, s) {
      $("#pageNo").val(n);
      $("#pageSize").val(s);
      $("#searchForm").submit();
      return false;
    }
  </script>
</head>
<body>
<ul class="nav nav-tabs">
  <li class="active"><a href="${ctxAdmin}/sys/article/">文章列表</a></li>
</ul>
<form:form id="searchForm" modelAttribute="model" action="${ctxAdmin}/sys/article" method="post" class="breadcrumb form-search form-inline">
  <sys:message content="${message}"/>
  <input id="pageNo" name="pageNo" type="hidden" value="${page.pageNo}"/>
  <input id="pageSize" name="pageSize" type="hidden" value="${page.pageSize}"/>
  <label>标题：</label> <form:input path="title" cssClass="form-control"></form:input>
  &nbsp;
  <label>文章类型：</label>
  <form:select path="articleType">
    <form:option value="" label="请选择"/>
    <c:forEach items="${atricleType}" var="atricleType">
      <form:option value="${atricleType.value}" label="${atricleType.label}"/>
    </c:forEach>
  </form:select>
  &nbsp;
  <label>状态：</label>
  <form:select path="isAuditing">
    <form:option value="" label="请选择"/>
      <c:forEach items="${isAuditingType}" var="isAuditingType">
        <form:option value="${isAuditingType.value}" label="${isAuditingType.label}"/>
      </c:forEach>
  </form:select>
  &nbsp;
  <button type="submit" class="btn btn-success">查询</button>
</form:form>
  <table class="table table-bordered table-condensed" style="font-size: 15px;">
    <tr>
      <th>标题</th>
      <th>模块类型</th>
      <th>所属用户</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
    <c:forEach items="${page.list}" var="article">
      <tr>
        <td>${article.title}</td>
        <td>
          <c:if test="${article.type == 'blog'}">
            博客
          </c:if>
          <c:if test="${article.type == 'share'}">
            分享
          </c:if>
          <c:if test="${article.type == 'talk'}">
            问答
          </c:if>
        </td>
        <td>${article.user.loginName}</td>
        <td>
          <c:if test="${article.isAuditing == '0'}">
            <span style="color: red;">未审核</span>
          </c:if>
          <c:if test="${article.isAuditing == '1'}">
            <span style="color:green;">已审核</span>
          </c:if>
          <c:if test="${article.isAuditing == '2'}">
            <span>未通过</span>
          </c:if>
        </td>
        <td>
          <a href="${ctxAdmin}/sys/article/edit?id=${article.id}">编辑</a>
          <a href="${ctxAdmin}/sys/article/delete?id=${article.id}" onclick="return confirmx('确认要删除该文章吗？', this.href)">删除</a>
        </td>
      </tr>
    </c:forEach>
  </table>
<div>${page}</div>
</body>
</html>

src/main/webapp/WEB-INF/views/modules/sys/dictForm.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp"%>
<html>
<head>
	<title>字典管理</title>
	<meta name="decorator" content="default"/>
	<script type="text/javascript">
		$(document).ready(function() {
			$("#value").focus();
			$("#inputForm").validate({
				submitHandler: function(form){
					loading('正在提交，请稍等...');
					form.submit();
				},
				errorContainer: "#messageBox",
				errorPlacement: function(error, element) {
					$("#messageBox").text("输入有误，请先更正。");
					if (element.is(":checkbox")||element.is(":radio")||element.parent().is(".input-append")){
						error.appendTo(element.parent().parent());
					} else {
						error.insertAfter(element);
					}
				}
			});
		});
	</script>
</head>
<body>
	<ul class="nav nav-tabs">
		<li><a href="${ctx}/sys/dict/">字典列表</a></li>
		<li class="active"><a href="${ctx}/sys/dict/form?id=${dict.id}">字典<shiro:hasPermission name="sys:dict:edit">${not empty dict.id?'修改':'添加'}</shiro:hasPermission><shiro:lacksPermission name="sys:dict:edit">查看</shiro:lacksPermission></a></li>
	</ul><br/>
	<form:form id="inputForm" modelAttribute="dict" action="${ctx}/sys/dict/save" method="post" class="form-horizontal">
		<form:hidden path="id"/>
		<sys:message content="${message}"/>
		<div class="control-group">
			<label class="control-label">键值:</label>
			<div class="controls">
				<form:input path="value" htmlEscape="false" maxlength="50" class="required"/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">标签:</label>
			<div class="controls">
				<form:input path="label" htmlEscape="false" maxlength="50" class="required"/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">类型:</label>
			<div class="controls">
				<form:input path="type" htmlEscape="false" maxlength="50" class="required abc"/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">描述:</label>
			<div class="controls">
				<form:input path="description" htmlEscape="false" maxlength="50" class="required"/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">排序:</label>
			<div class="controls">
				<form:input path="sort" htmlEscape="false" maxlength="11" class="required digits"/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">备注:</label>
			<div class="controls">
				<form:textarea path="remarks" htmlEscape="false" rows="3" maxlength="200" class="input-xlarge"/>
			</div>
		</div>
		<div class="form-actions">
			<shiro:hasPermission name="sys:dict:edit"><input id="btnSubmit" class="btn btn-primary" type="submit" value="保 存"/>&nbsp;</shiro:hasPermission>
			<input id="btnCancel" class="btn" type="button" value="返 回" onclick="history.go(-1)"/>
		</div>
	</form:form>
</body>
</html>

src/main/webapp/WEB-INF/views/modules/sys/menuTree.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp"%>
<div class="accordion" id="menu-${param.parentId}">
	<c:set var="menuList" value="${fns:getMenuList()}"/>
	<c:set var="firstMenu" value="true"/>
	<c:forEach items="${menuList}" var="menu" varStatus="idxStatus"><c:if test="${menu.parent.id eq (not empty param.parentId ? param.parentId:1)&&menu.isShow eq '1'}">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a class="accordion-toggle" data-toggle="collapse" data-parent="#menu-${param.parentId}" data-href="#collapse-${menu.id}" href="#collapse-${menu.id}" title="${menu.remarks}"><i class="icon-chevron-${not empty firstMenu && firstMenu ? 'down' : 'right'}"></i>&nbsp;${menu.name}</a>
		</div>
		<div id="collapse-${menu.id}" class="accordion-body collapse ${not empty firstMenu && firstMenu ? 'in' : ''}">
			<div class="accordion-inner">
				<ul class="nav nav-list">
					<c:forEach items="${menuList}" var="menu2"><c:if test="${menu2.parent.id eq menu.id&&menu2.isShow eq '1'}">
					<li><a data-href=".menu3-${menu2.id}" href="${fn:indexOf(menu2.href, '://') eq -1 ? ctx : ''}${not empty menu2.href ? menu2.href : '/404'}" target="${not empty menu2.target ? menu2.target : 'mainFrame'}" ><i class="icon-${not empty menu2.icon ? menu2.icon : 'circle-arrow-right'}"></i>&nbsp;${menu2.name}</a>
						<ul class="nav nav-list hide" style="margin:0;padding-right:0;">
							<c:forEach items="${menuList}" var="menu3"><c:if test="${menu3.parent.id eq menu2.id&&menu3.isShow eq '1'}">
							<li class="menu3-${menu2.id} hide">
								<a href="${fn:indexOf(menu3.href, '://') eq -1 ? ctx : ''}
								${not empty menu3.href ? menu3.href : '/404'}"
								   target="${not empty menu3.target ? menu3.target : 'mainFrame'}" >
									<i class="icon-${not empty menu3.icon ? menu3.icon : 'circle-arrow-right'}"></i>&nbsp;${menu3.name}</a>
							</li>
							</c:if>
						</c:forEach>
						</ul></li>
						<c:set var="firstMenu" value="false"/></c:if>
					</c:forEach>
				</ul>
			</div>
		</div>
	</div>
	</c:if>
</c:forEach>
</div>

src/main/webapp/WEB-INF/views/modules/sys/roleList.jsp
]<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp"%>
<html>
<head>
	<title>角色管理</title>
	<meta name="decorator" content="default"/>
</head>
<body>
	<ul class="nav nav-tabs">
		<li class="active"><a href="${ctx}/sys/role/">角色列表</a></li>
		<shiro:hasPermission name="sys:role:edit"><li><a href="${ctx}/sys/role/form">角色添加</a></li></shiro:hasPermission>
	</ul>
	<sys:message content="${message}"/>
	<table id="contentTable" class="table table-striped table-bordered table-condensed">
		<tr>
			<th>角色名称</th>
			<th>英文名称</th>
			<shiro:hasPermission name="sys:role:edit">
				<th>操作</th>
			</shiro:hasPermission>
		</tr>
		<c:forEach items="${list}" var="role">
			<tr>
				<td><a href="form?id=${role.id}">${role.name}</a></td>
				<td><a href="form?id=${role.id}">${role.enname}</a></td>

				<shiro:hasPermission name="sys:role:edit"><td>
					<c:if test="${(role.sysData eq fns:getDictValue('是', 'yes_no', '1') && fns:getUser().admin)||!(role.sysData eq fns:getDictValue('是', 'yes_no', '1'))}">
						<a href="${ctx}/sys/role/form?id=${role.id}">修改</a>
					</c:if>
					<a href="${ctx}/sys/role/delete?id=${role.id}" onclick="return confirmx('确认要删除该角色吗？', this.href)">删除</a>
				</td></shiro:hasPermission>	
			</tr>
		</c:forEach>
	</table>
</body>
</html>